version: '3'
services:

  php:
    build:
      args:
        user: syam
        uid: 1000
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/var/www/
      - $HOME/.composer/:$HOME/.composer/
    environment:
      - "DB_HOST=mysql"
      - "DB_DATABASE=DSP"
      - "DB_USERNAME=DSP"
      - "DB_PASSWORD=DSP"
    networks:
      - service-network

  nginx:
    image: nginx:alpine
    container_name: nginx-web-server
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - service-network

  mysql:
    image: mariadb:10.5.8
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=DSP"
      - "MYSQL_DATABASE=DSP"
      - "MYSQL_USER=DSP"
      - "MYSQL_PASSWORD=DSP"
    ports:
        - "3306:3306"
    networks:
      - service-network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    networks:
      - service-network


volumes:
  mysqldata:

networks:
  service-network:
    driver: bridge
